spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://db.xeyuvlwepepvmenzwarq.supabase.co:5432/postgres?user=postgres&password=gradify@2026
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.password=gradify@2026
spring.jpa.show-sql=true