---
- name: Deploy Gradify K8s manifests using Roles
  hosts: localhost
  connection: local

  vars_files:
    - secrets.yml

  vars:
    deploy_dir: /tmp/gradify-k8s-deploy

  roles:
    - role: minikube_setup
    - role: k8s_config
    - role: gradify_deploy
